make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pkg_libschc test
test_compiled_unittests (__main__.TestCompiledUnittests) ... ok
test_compress_rule_2_down (__main__.TestFragmentation) ... ok
test_compress_rule_2_up (__main__.TestFragmentation) ... ok
test_decompress_rule_2_down (__main__.TestFragmentation) ... ok
test_decompress_rule_2_up (__main__.TestFragmentation) ... ok
test_compress_init_parse_error (__main__.TestSelfTest) ... ok
test_compress_init_success (__main__.TestSelfTest) ... ok
test_compress_no_input (__main__.TestSelfTest) ... ok
test_compress_success (__main__.TestSelfTest) ... ok
test_compress_usage (__main__.TestSelfTest) ... ok
test_compress_wrong_device_id (__main__.TestSelfTest) ... ok
test_decompress_no_input (__main__.TestSelfTest) ... ok
test_decompress_success (__main__.TestSelfTest) ... ok
test_decompress_usage (__main__.TestSelfTest) ... ok
test_fragment_init (__main__.TestSelfTest) ... ok
test_fragment_no_input (__main__.TestSelfTest) ... ok
test_fragment_no_rule (__main__.TestSelfTest) ... ok
test_fragment_success_ack_always_001 (__main__.TestSelfTest) ... ok
test_fragment_success_ack_always_all1 (__main__.TestSelfTest) ... ok
test_fragment_success_ack_on_error_10 (__main__.TestSelfTest) ... ok
test_fragment_success_ack_on_error_all1 (__main__.TestSelfTest) ... ok
test_fragment_success_no_ack (__main__.TestSelfTest) ... ok
test_fragment_success_no_frag (__main__.TestSelfTest) ... ok
test_fragment_usage (__main__.TestSelfTest) ... ok
test_input_add (__main__.TestSelfTest) ... ok
test_input_add_full_buf_mod_128 (__main__.TestSelfTest) ... ok
test_input_add_full_buf_not_mod_128 (__main__.TestSelfTest) ... ok
test_input_reset (__main__.TestSelfTest) ... ok
test_input_usage (__main__.TestSelfTest) ... ok
test_output_copy (__main__.TestSelfTest) ... ok
test_output_show (__main__.TestSelfTest) ... ok
test_output_usage (__main__.TestSelfTest) ... ok
test_reassemble_no_frag (__main__.TestSelfTest) ... ok
test_reassemble_no_input (__main__.TestSelfTest) ... ok
test_reassemble_success_ack_always (__main__.TestSelfTest) ... ERROR
test_reassemble_success_no_ack (__main__.TestSelfTest) ... ERROR
ERROR
test_reassemble_usage (__main__.TestSelfTest) ... ok
test_set_ack_success (__main__.TestSelfTest) ... ok
test_set_ack_too_large (__main__.TestSelfTest) ... ok
test_set_ack_usage (__main__.TestSelfTest) ... ok
test_timer_success (__main__.TestSelfTest) ... ok

======================================================================
ERROR: test_reassemble_success_ack_always (__main__.TestSelfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 651, in test_reassemble_success_ack_always
    self.input(
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 42, in input
    self.expect_od_dump_of(input_hex[:self.MAX])
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 64, in expect_od_dump_of
    self.spawn.expect_exact("{:08x}{}".format(i * 16, od_bytes))
  File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f8fe3e2f580>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): '000000  17  51  FE  80  00  00  00\r\n\r\n> '
before (last 100 chars): '\r\n00000000  17  51  FE  80  00  00  00\r\n\r\n> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 4003718
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: '00000000  17  51  FE  80  00  00  00  00'

======================================================================
ERROR: test_reassemble_success_no_ack (__main__.TestSelfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 622, in test_reassemble_success_no_ack
    self.input(b"\x15\x98\xa6\x43\xbf\xc8\x00\x00\x00\x00")
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 42, in input
    self.expect_od_dump_of(input_hex[:self.MAX])
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 64, in expect_od_dump_of
    self.spawn.expect_exact("{:08x}{}".format(i * 16, od_bytes))
  File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f8fe3e2f580>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): '00  15  98  A6  43  BF  80  00  00\r\n\r\n> '
before (last 100 chars): '\r\n00000000  15  98  A6  43  BF  80  00  00\r\n\r\n> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 4003718
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: '00000000  15  98  A6  43  BF  C8  00  00'

======================================================================
ERROR: test_reassemble_success_no_ack (__main__.TestSelfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/jenkins-slave/workspace/RIOT/tests/pkg_libschc/tests/01-run.py", line 74, in tearDown
    self.spawn.expect_exact("Successfully reset output buffer.")
  File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f8fe3e2f580>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): 'ell: command not found: outpu\r\n> '
before (last 100 chars): '\r\n> outpu reset\r\nshell: command not found: outpu\r\n> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 4003718
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: 'Successfully reset output buffer.'

----------------------------------------------------------------------
Ran 41 tests in 73.712s

FAILED (errors=3)
make: *** [/srv/jenkins-slave/workspace/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1

Return value: 2
